syntax = "proto3";

package grpcimpl.boss_config.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service BossService {
  rpc SetFestival(SetFestivalRequest) returns (google.protobuf.Empty);
  rpc SetVSSetting(SetVSSettingRequest) returns (google.protobuf.Empty);
}

enum Language {
  EUROPEAN_GERMAN = 0;
  EUROPEAN_ENGLISH = 1;
  EUROPEAN_SPANISH = 2;
  EUROPEAN_FRENCH = 3;
  EUROPEAN_ITALIAN = 4;
  JAPANESE = 5;
  AMERICAN_ENGLISH = 6;
  AMERICAN_SPANISH = 7;
  AMERICAN_FRENCH = 8;
}

enum Gamemode {
  TURF_WAR = 0;
  SPLAT_ZONES = 1;
  TOWER_CONTROL = 2;
  RAINMAKER = 3;
}

enum Stage {
  URCHIN_UNDERPASS = 0;
  WALLEYE_WAREHOUSE = 1;
  SALTSPRAY_RIG = 2;
  AROWANA_MALL = 3;
  BLACKBELLY_SKATEPARK = 4;
  CAMP_TRIGGERFISH = 5;
  PORT_MACKEREL = 6;
  KELP_DOME = 7;
  MORAY_TOWERS = 8;
  BLUEFIN_DEPOT = 9;
  HAMMERHEAD_BRIDGE = 10;
  FLOUNDER_HEIGHTS = 11;
  MUSEUM_D_ALFONSINO = 12;
  ANCHO_V_GAMES = 13;
  PIRANHA_PIT = 14;
  MAHIMAHI_RESORT = 15;
}

message Color {
  uint32 r = 1;
  uint32 g = 2;
  uint32 b = 3;
  uint32 a = 4;
}

message DialogueLine {
  enum Command { SPEAK_RAW_TEXT = 0; }
  enum Emotion {
    NORMAL_TALK = 0;
    GREETING = 1;
    HAPPY = 2;
    ANGRY = 3;
    SURPRISED = 4;
    BORED = 5;
    FEED = 6;
  }
  enum Speaker { IDOL_LEFT = 0; IDOL_RIGHT = 1; IDOL_ALL = 2; }

  Command command = 1;
  Emotion emotion = 2;
  Speaker speaker = 3;
  string text = 4;
  bool wait_button = 5;
}

message LanguageDialogue {
  Language language = 1;
  repeated DialogueLine lines = 2;
}

message LanguageStringPair {
  Language language = 1;
  string value = 2;
}

message TeamInfo {
  Color color = 1;
  repeated LanguageStringPair names = 2;
  repeated LanguageStringPair short_names = 3;
}

message SetFestivalRequest {
  int32 id = 1;
  int32 battle_result_rate = 2;
  bool low_population_not_jp = 3;
  bool separate_matching_jp = 4;
  repeated LanguageDialogue announce_news = 5;
  repeated LanguageDialogue start_news = 6;
  repeated LanguageDialogue result_a_news = 7;
  repeated LanguageDialogue result_b_news = 8;
  Gamemode gamemode = 9;
  repeated Stage stages = 10;
  TeamInfo team_a = 11;
  TeamInfo team_b = 12;
  Color neutral_color = 13;
  google.protobuf.Timestamp announce_time = 14;
  google.protobuf.Timestamp start_time = 15;
  google.protobuf.Timestamp end_time = 16;
  google.protobuf.Timestamp result_time = 17;
  google.protobuf.Timestamp after_fes_bonus_start = 18;
  Language backup_language = 19;
  bytes body_team_a = 20;
  bytes body_team_b = 21;
  bytes panel_texture = 22;
}

message MapFirstAppearance {
  uint32 map_id = 1;
  google.protobuf.Timestamp date = 2;
}

message RuleFirstAppearance {
  Gamemode gachi_rule = 1;
  google.protobuf.Timestamp date = 2;
}

message WeaponUnlockEntry {
  uint32 weapon_set_id = 1;
  google.protobuf.Timestamp date = 2;
}

message VSSettingPhase {
  Gamemode gachi_rule = 1;
  Gamemode regular_rule = 2;
  repeated uint32 gachi_stages = 3;
  repeated uint32 regular_stages = 4;
  uint32 duration = 5;
}

message VSSettingConfig {
  uint32 add_first_matching_time = 1;
  uint32 add_matching_time = 2;
  google.protobuf.Timestamp after_fes_bonus_start = 3;
  uint32 bottleneck_threshold_frame = 4;
  bool disconnect_by_memory_hash = 5;
  google.protobuf.Timestamp datetime = 6;
  repeated MapFirstAppearance map_first_appear = 7;
  repeated VSSettingPhase phases = 8;
  repeated RuleFirstAppearance rule_first_appear = 9;
  uint32 timeout_after_join = 10;
  uint32 version = 11;
  uint32 wait_matching_time = 12;
  repeated WeaponUnlockEntry weapon_unlock = 13;
  bool web_post = 14;
}

message SetVSSettingRequest {
  VSSettingConfig config = 1;
}
