syntax = "proto3";

package grpcimpl.friends.v1;

import "google/protobuf/empty.proto";
import "common.proto";

service FriendsService {
  rpc SendNotification(SendNotificationRequest) returns (google.protobuf.Empty);
  rpc GetConnectedClientCount(google.protobuf.Empty) returns (GetConnectedClientCountResponse);
}

message SendNotificationRequest {
  grpcimpl.common.ClientInfo clientInfo = 1;
  NintendoNotificationType type = 2;
  uint32 sender = 3;
  AnyDataHolder data = 4;
}

message AnyDataHolder {
  string type = 1;
  bytes data = 2;
}

enum NintendoNotificationType {
  NONE = 0;
  WENT_OFFLINE = 10;
  MII_CHANGED = 21;
  PREFERENCES_UPDATED = 23;
  PRESENCE_UPDATED = 24;
  FRIEND_REMOVED = 26;
  FRIEND_REQUEST_RECEIVED = 27;
  FRIEND_REQUEST_ACCEPTED = 30;
  COMMENT_CHANGED = 33;
}

message GetConnectedClientCountResponse {
  uint32 count = 1;
}