syntax = "proto3";

package grpcimpl.splatoon.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "common.proto";

service SplatoonService {
  rpc SendNotification(SendNotificationRequest) returns (google.protobuf.Empty);
  rpc RequestProbeInitiationExt(ProbeRequest) returns (google.protobuf.Empty);
  rpc GetConnectedClientCount(google.protobuf.Empty) returns (GetConnectedClientCountResponse);
  rpc GetLobbyCount(google.protobuf.Empty) returns (GetLobbyCountResponse);

  // This could be optimized in the future by doing pagination or something similar, but for now this is good enough.
  rpc GetExistingLobbies(google.protobuf.Empty) returns (GetExistingLobbiesResponse);
}

message SendNotificationRequest {
  grpcimpl.common.ClientInfo clientInfo = 1;
  NotificationType type = 2;
  uint32 srcPid = 3;
  uint32 param1 = 4;
  uint32 param2 = 5;
  string strParam = 6;
  uint32 param3 = 7;
}

enum NotificationType {
  NONE = 0;
  NEW_PARTICIPANT = 3001;
  PARTICIPATION_CANCELLED = 3002;
  PARTICIPANT_DISCONNECTED = 3007;
  PARTICIPATION_ENDED = 3008;
  OWNERSHIP_CHANGED = 4000;
  GATHERING_UNREGISTERED = 109000;
  HOST_CHANGED = 110000;
  MATCHMAKE_REFEREE_ROUND_STARTED = 116000;
  SYSTEM_PASSWORD_CHANGED = 120000;
  SYSTEM_PASSWORD_CLEARED = 121000;
  SWITCH_GATHERING = 122000;
}

message ProbeRequest {
  grpcimpl.common.ClientInfo clientInfo = 1;
  bytes probe = 2;
}

message GetConnectedClientCountResponse {
  uint32 count = 1;
}

message GetLobbyCountResponse {
  uint32 count = 1;
}

message GetExistingLobbiesResponse {
  repeated Lobby lobbies = 1;
}

message Lobby {
  // Gathering info
  uint32 gId = 1;
  uint32 ownerPid = 2;
  uint32 hostPid = 3;
  uint32 minParticipants = 4;
  uint32 maxParticipants = 5;
  uint32 participationPolicy = 6;
  uint32 policyArgument = 7;
  uint32 flags = 8;
  uint32 state = 9;
  string description = 10;

  // Matchmake session info
  uint32 gameMode = 11;
  repeated uint32 attributes = 12;
  bool openParticipation = 13;
  uint32 matchmakeSystemType = 14;
  uint32 progressScore = 15; // uint8
  uint32 option0 = 16;
  bool userPasswordEnabled = 17;
  bool systemPasswordEnabled = 18;
  google.protobuf.Timestamp startedTime = 19;

  repeated uint32 playerPids = 20;
}