#ifndef SPLATOON_SERVER_STATUS_CODES_HPP
#define SPLATOON_SERVER_STATUS_CODES_HPP

#include <map>
#include <string>

namespace http {

#define HTTP_STATUS_CONTINUE 100
#define HTTP_STATUS_SWITCHING_PROTOCOLS 101
#define HTTP_STATUS_PROCESSING 102
#define HTTP_STATUS_EARLY_HINTS 103

#define HTTP_STATUS_OK 200
#define HTTP_STATUS_CREATED 201
#define HTTP_STATUS_ACCEPTED 202
#define HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION 203
#define HTTP_STATUS_NO_CONTENT 204
#define HTTP_STATUS_RESET_CONTENT 205
#define HTTP_STATUS_PARTIAL_CONTENT 206
#define HTTP_STATUS_MULTI_STATUS 207
#define HTTP_STATUS_ALREADY_REPORTED 208
#define HTTP_STATUS_IM_USED 226

#define HTTP_STATUS_MULTIPLE_CHOICES 300
#define HTTP_STATUS_MOVED_PERMANENTLY 301
#define HTTP_STATUS_FOUND 302
#define HTTP_STATUS_SEE_OTHER 303
#define HTTP_STATUS_NOT_MODIFIED 304
//#define HTTP_STATUS_USE_PROXY 305 // Deprecated
//#define HTTP_STATUS_SWITCH_PROXY 306 // Deprecated
#define HTTP_STATUS_TEMPORARY_REDIRECT 307
#define HTTP_STATUS_PERMANENT_REDIRECT 308

#define HTTP_STATUS_BAD_REQUEST 400
#define HTTP_STATUS_UNAUTHORIZED 401
#define HTTP_STATUS_PAYMENT_REQUIRED 402
#define HTTP_STATUS_FORBIDDEN 403
#define HTTP_STATUS_NOT_FOUND 404
#define HTTP_STATUS_METHOD_NOT_ALLOWED 405
#define HTTP_STATUS_NOT_ACCEPTABLE 406
#define HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED 407
#define HTTP_STATUS_REQUEST_TIMEOUT 408
#define HTTP_STATUS_CONFLICT 409
#define HTTP_STATUS_GONE 410
#define HTTP_STATUS_LENGTH_REQUIRED 411
#define HTTP_STATUS_PRECONDITION_FAILED 412
#define HTTP_STATUS_PAYLOAD_TOO_LARGE 413
#define HTTP_STATUS_URI_TOO_LONG 414
#define HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE 415
#define HTTP_STATUS_RANGE_NOT_SATISFIABLE 416
#define HTTP_STATUS_EXPECTATION_FAILED 417
#define HTTP_STATUS_IM_A_TEAPOT 418
#define HTTP_STATUS_MISDIRECTED_REQUEST 421
#define HTTP_STATUS_UNPROCESSABLE_CONTENT 422
#define HTTP_STATUS_LOCKED 423
#define HTTP_STATUS_FAILED_DEPENDENCY 424
#define HTTP_STATUS_TOO_EARLY 425
#define HTTP_STATUS_UPGRADE_REQUIRED 426
#define HTTP_STATUS_PRECONDITION_REQUIRED 428
#define HTTP_STATUS_TOO_MANY_REQUESTS 429
#define HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS 451

#define HTTP_STATUS_INTERNAL_SERVER_ERROR 500
#define HTTP_STATUS_NOT_IMPLEMENTED 501
#define HTTP_STATUS_BAD_GATEWAY 502
#define HTTP_STATUS_SERVICE_UNAVAILABLE 503
#define HTTP_STATUS_GATEWAY_TIMEOUT 504
#define HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED 505
#define HTTP_STATUS_VARIANT_ALSO_NEGOTIATES 506
#define HTTP_STATUS_INSUFFICIENT_STORAGE 507
#define HTTP_STATUS_LOOP_DETECTED 508
#define HTTP_STATUS_NOT_EXTENDED 510
#define HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED 511

const std::map<int, std::string> STATUS_CODE_MSG = {
    // Information
    {HTTP_STATUS_CONTINUE, "Continue"},
    {HTTP_STATUS_SWITCHING_PROTOCOLS, "Switching Protocols"},
    {HTTP_STATUS_PROCESSING, "Processing"},
    {HTTP_STATUS_EARLY_HINTS, "Early Hints"},
    // Success
    {HTTP_STATUS_OK, "OK"},
    {HTTP_STATUS_CREATED, "Created"},
    {HTTP_STATUS_ACCEPTED, "Accepted"},
    {HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION, "Non-Authoritative Information"},
    {HTTP_STATUS_NO_CONTENT, "No Content"},
    {HTTP_STATUS_RESET_CONTENT, "Reset Content"},
    {HTTP_STATUS_PARTIAL_CONTENT, "Partial Content"},
    {HTTP_STATUS_MULTI_STATUS, "Multi-Status"},
    {HTTP_STATUS_ALREADY_REPORTED, "Already Reported"},
    {HTTP_STATUS_IM_USED, "IM Used"},
    // Redirection
    {HTTP_STATUS_MULTIPLE_CHOICES, "Multiple Choices"},
    {HTTP_STATUS_MOVED_PERMANENTLY, "Moved Permanently"},
    {HTTP_STATUS_FOUND, "Found"},
    {HTTP_STATUS_SEE_OTHER, "See Other"},
    {HTTP_STATUS_NOT_MODIFIED, "Not Modified"},
    // {HTTP_STATUS_USE_PROXY, "Use Proxy"}, // Deprecated
    // {HTTP_STATUS_SWITCH_PROXY, "Switch Proxy"}, // Deprecated
    {HTTP_STATUS_TEMPORARY_REDIRECT, "Temporary Redirect"},
    {HTTP_STATUS_PERMANENT_REDIRECT, "Permanent Redirect"},
    // Error
    {HTTP_STATUS_BAD_REQUEST, "Bad Request"},
    {HTTP_STATUS_UNAUTHORIZED, "Unauthorized"},
    {HTTP_STATUS_PAYMENT_REQUIRED, "Payment Required"},
    {HTTP_STATUS_FORBIDDEN, "Forbidden"},
    {HTTP_STATUS_NOT_FOUND, "Not Found"},
    {HTTP_STATUS_METHOD_NOT_ALLOWED, "Method Not Allowed"},
    {HTTP_STATUS_NOT_ACCEPTABLE, "Not Acceptable"},
    {HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED, "Proxy Authentication Required"},
    {HTTP_STATUS_REQUEST_TIMEOUT, "Request Timeout"},
    {HTTP_STATUS_CONFLICT, "Conflict"},
    {HTTP_STATUS_GONE, "Gone"},
    {HTTP_STATUS_LENGTH_REQUIRED, "Length Required"},
    {HTTP_STATUS_PRECONDITION_FAILED, "Precondition Failed"},
    {HTTP_STATUS_PAYLOAD_TOO_LARGE, "Payload Too Large"},
    {HTTP_STATUS_URI_TOO_LONG, "URI Too Long"},
    {HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE, "Unsupported Media Type"},
    {HTTP_STATUS_RANGE_NOT_SATISFIABLE, "Range Not Satisfiable"},
    {HTTP_STATUS_EXPECTATION_FAILED, "Expectation Failed"},
    {HTTP_STATUS_IM_A_TEAPOT, "I'm a teapot"},
    {HTTP_STATUS_MISDIRECTED_REQUEST, "Misdirected Request"},
    {HTTP_STATUS_UNPROCESSABLE_CONTENT, "Unprocessable Content"},
    {HTTP_STATUS_LOCKED, "Locked"},
    {HTTP_STATUS_FAILED_DEPENDENCY, "Failed Dependency"},
    {HTTP_STATUS_TOO_EARLY, "Too Early"},
    {HTTP_STATUS_UPGRADE_REQUIRED, "Upgrade Required"},
    {HTTP_STATUS_PRECONDITION_REQUIRED, "Precondition Required"},
    {HTTP_STATUS_TOO_MANY_REQUESTS, "Too Many Requests"},
    {HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE, "Request Header Fields Too Large"},
    {HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS, "Unavailable For Legal Reasons"},
    // Server error
    {HTTP_STATUS_INTERNAL_SERVER_ERROR, "Internal Server Error"},
    {HTTP_STATUS_NOT_IMPLEMENTED, "Not Implemented"},
    {HTTP_STATUS_BAD_GATEWAY, "Bad Gateway"},
    {HTTP_STATUS_SERVICE_UNAVAILABLE, "Service Unavailable"},
    {HTTP_STATUS_GATEWAY_TIMEOUT, "Gateway Timeout"},
    {HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED, "HTTP Version Not Supported"},
    {HTTP_STATUS_VARIANT_ALSO_NEGOTIATES, "Variant Also Negotiates"},
    {HTTP_STATUS_INSUFFICIENT_STORAGE, "Insufficient Storage"},
    {HTTP_STATUS_LOOP_DETECTED, "Loop Detected"},
    {HTTP_STATUS_NOT_EXTENDED, "Not Extended"},
    {HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED, "Network Authentication Required"}
};

} // namespace http

#endif //SPLATOON_SERVER_STATUS_CODES_HPP
